import numpy as np
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score, KFold, learning_curve, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, classification_report,  roc_auc_score, confusion_matrix, precision_score, recall_score, f1_score, ConfusionMatrixDisplay, roc_curve
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_selection import mutual_info_classif, SequentialFeatureSelector
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier
import joblib
import seaborn as sns

data = pd.read_csv("C:/Users/edwar/Downloads/archive/heart_disease_dataset.csv")
df1 = data.copy()

'''print(df1.isnull().sum())       # Alcohol Intake got 340 row is None, which python will assume it as missing value. 
print(df1.info())'''
df1["Alcohol Intake"] = df1["Alcohol Intake"].fillna("Heavy")       # .fillna used to replace the missing value with a specific value. 

#df1.to_csv("heart_disease_cleaned.csv", index=False)
df14 = df1.copy()
important_features = ["Age", "Cholesterol", "Gender", "Blood Pressure", "Heart Rate", "Exercise Hours", "Family History", "Smoking"]
#"Age", "Cholesterol", "Gender", "Blood Pressure", "Heart Rate", "Exercise Hours", "Family History", "Smoking"
#XX = df14[important_features].copy()
XX = df14.drop(columns=["Heart Disease"])
yy = df14["Heart Disease"].copy()

label_encoders = {}
for col in XX.select_dtypes(include=['str', 'string', 'object']).columns:
    le = LabelEncoder()
    XX[col] = le.fit_transform(XX[col])      # Look the entire specific column and learn all unique category, then assign a unique integer to each category
    label_encoders[col] = le

'''Generate the Correlation Matrix Image
plt.figure(figsize=(16,14))

sns.heatmap(XX.corr(),
            annot=True,
            cmap="coolwarm")

plt.savefig('correlation.png', dpi = 300) 
'''

yy = LabelEncoder().fit_transform(yy)

# Split into training (80%) and testing (20%) sets
X_train_raw, X_test_raw, y_train, y_test = train_test_split(XX, yy, test_size=0.2, stratify=yy, random_state=42)
# stratify is used to prevent the model from being trained on a biased sample, it ensure both set got equal % of health and heart disease patients. 
mask = pd.Series(True, index=X_train_raw.index)
for col in ["Age", "Cholesterol", "Blood Pressure", "Heart Rate", "Exercise Hours"]:

    Q1 = X_train_raw[col].quantile(0.25)
    Q3 = X_train_raw[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = X_train_raw[(X_train_raw[col] < lower) |
                        (X_train_raw[col] > upper)]

    print(col, len(outliers))

    mask &= (X_train_raw[col] >= lower) & (X_train_raw[col] <= upper)
X_train_raw = X_train_raw[mask]
y_train = y_train[mask]

# To put all the features on the exact same scale to prevent some algo will thing the larger number of other feaure more important
X_train = X_train_raw.copy()
X_test = X_test_raw.copy()
scaler = StandardScaler()
num_cols = ["Age", "Cholesterol", "Blood Pressure", "Heart Rate", "Exercise Hours", "Stress Level", "Blood Sugar"] #, "Blood Pressure", "Heart Rate", "Exercise Hours", "Stress Level", "Blood Sugar"


X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

'''
mi_scores = mutual_info_classif(X_train, y_train, discrete_features='auto', random_state=42)
mi_df = pd.DataFrame({'Feature': XX.columns, 'Mutual Information': mi_scores})
mi_df = mi_df.sort_values(by="Mutual Information", ascending=False)

print("\n--- Feature Importance ---")
print(mi_df)
'''


base_models = [
    ('lr', LogisticRegression(random_state=42, C=0.1)),
    ('knn', KNeighborsClassifier(
        n_neighbors=9,
        weights="uniform",
        metric="euclidean"
    ))
]

#Stacking Classifier, output generated by beta model used as a new input feature to train a meta level.
#Instead of directly using the prediction from beta model againt with actual target.
heart_net = StackingClassifier(
    estimators=base_models,
    final_estimator=LogisticRegression(C=1),
    stack_method='predict_proba',
    cv=5
)

heart_net.fit(X_train, y_train)


y_pred = heart_net.predict(X_test)


# Predicted probabilities for the positive class
y_prob = heart_net.predict_proba(X_test)[:, 1]
auc = roc_auc_score(y_test, y_prob)

precision = precision_score(y_test, y_pred)

recall = recall_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred)

# Print the weights assigned to [LR_probabilities, KNN_probabilities]
print("Meta-estimator weights:", heart_net.final_estimator_.coef_)
print("\n===============================")
print(" Hybrid KNN + LR Results")
print("===============================\n")

print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1-score : {f1:.4f}")
print(f"ROC-AUC  : {auc:.4f}")
print(
    f"Accuracy: {accuracy_score(y_test, y_pred)*100:.2f}%"
)
'''print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))'''

train_sizes, train_scores, valid_scores = learning_curve(
    heart_net,
    scaler.fit_transform(XX),
    yy,
    cv=5,
    scoring="accuracy",
    train_sizes=np.linspace(0.1,1.0,10),
    random_state=42
)

train_mean = train_scores.mean(axis=1)
valid_mean = valid_scores.mean(axis=1)
print(train_mean)
print(valid_mean)


'''# Generate and plot the confusion matrix automatically
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Healthy", "Heart Disease"])

# Plot with a blue color map
disp.plot(cmap="Blues", values_format="d")

plt.title("Confusion Matrix", fontsize=14, fontweight='bold')

# Save the plot (Optional)
plt.savefig("confusion_matrix_sklearn.png", dpi=300, bbox_inches='tight')'''


'''# Save the model
joblib.dump(heart_net, 'heart_net.pkl')


# Save the dictionary of label encoders you created
joblib.dump(label_encoders, 'label_encoders.pkl')


# SAVE THE SCALER
joblib.dump(scaler, 'scaler.pkl')


print("Model and Encoders saved successfully!")'''

'''# ROC Curve
fpr, tpr, thresholds = roc_curve(y_test, y_prob)


plt.figure(figsize=(6,6))
plt.plot(fpr, tpr, label=f"AUC = {auc:.4f}")
plt.plot([0,1], [0,1], linestyle='--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Receiver Operating Characteristic (ROC)")
plt.legend(loc="lower right")
plt.grid(True)
plt.savefig("AUC-ROC.png", dpi=300)'''