from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
from sklearn.model_selection import StratifiedKFold, cross_validate, train_test_split, cross_val_score, KFold, learning_curve, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, classification_report,  roc_auc_score, confusion_matrix, precision_score, recall_score, f1_score, ConfusionMatrixDisplay, roc_curve
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_selection import mutual_info_classif, SequentialFeatureSelector
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier
import joblib
import seaborn as sns
from sklearn.impute import SimpleImputer

MODEL_DIR = Path("saved_models")
MODEL_DIR.mkdir(parents=True, exist_ok=True)
 
SCALER_PATH = MODEL_DIR / "heart_scaler.joblib"
COLUMNS_PATH = MODEL_DIR / "heart_feature_columns.joblib"
MODEL_PATH = MODEL_DIR / "knn_lr_model.joblib"

df = pd.read_csv("C:/Users/edwar/Downloads/heart_disease_dataset.csv")
# ==========================
# Separate Features and Target
# ==========================

X = df.drop("Heart Disease", axis=1)
#X = df[["Age", "Cholesterol"]]
y = df["Heart Disease"]

# ==========================
# Detect Numerical and Categorical Columns
# ==========================

numerical_columns = X.select_dtypes(include=["int64", "float64"]).columns
categorical_columns = X.select_dtypes(include=["str"]).columns

print("Numerical Columns:")
print(numerical_columns)

print("\nCategorical Columns:")
print(categorical_columns)

# ==========================
# Handle Missing Values
# ==========================

num_imputer = SimpleImputer(strategy="median")
X[numerical_columns] = num_imputer.fit_transform(X[numerical_columns])

cat_imputer = SimpleImputer(strategy="most_frequent")
X[categorical_columns] = cat_imputer.fit_transform(X[categorical_columns])

# ==========================
# Outlier Removal
# ==========================

mask = pd.Series(True, index=X.index)
for col in numerical_columns:

    Q1 = X[col].quantile(0.25)
    Q3 = X[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = X[(X[col] < lower) |
                (X[col] > upper)]

    print(col, len(outliers))

    mask &= (X[col] >= lower) & (X[col] <= upper)
X = X[mask]
y = y[mask]

# ==========================
# One-Hot Encoding
# ==========================

X = pd.get_dummies(
    X,
    columns=categorical_columns,
    drop_first=True
)

# ==========================
# Feature Scaling
# ==========================

scaler = StandardScaler()
X[numerical_columns] = scaler.fit_transform(X[numerical_columns])

# ==========================
# Train-Test Split
# ==========================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

'''Generate the Correlation Matrix Image
plt.figure(figsize=(16,14))

sns.heatmap(XX.corr(),
            annot=True,
            cmap="coolwarm")

plt.savefig('correlation.png', dpi = 300) 
'''

'''
mi_scores = mutual_info_classif(X_train, y_train, discrete_features='auto', random_state=42)
mi_df = pd.DataFrame({'Feature': XX.columns, 'Mutual Information': mi_scores})
mi_df = mi_df.sort_values(by="Mutual Information", ascending=False)

print("\n--- Feature Importance ---")
print(mi_df)
'''


base_models = [
    ('lr', LogisticRegression(random_state=42, C=0.1)),
    ('knn', KNeighborsClassifier(
        n_neighbors=27,
        weights="uniform",
        metric="euclidean"
    ))
]

#Stacking Classifier, output generated by beta model used as a new input feature to train a meta level.
#Instead of directly using the prediction from beta model againt with actual target.
heart_net = StackingClassifier(
    estimators=base_models,
    final_estimator=LogisticRegression(C=1),
    stack_method='predict_proba',
    cv=5
)

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

cv_result = cross_validate(
    estimator=heart_net,
    X=X_train,
    y=y_train,
    cv=cv,
    scoring=['accuracy', 'roc_auc', 'recall', 'f1'],
    return_train_score=False
)

heart_net.fit(X_train, y_train)


y_pred = heart_net.predict(X_test)


# Predicted probabilities for the positive class
y_prob = heart_net.predict_proba(X_test)[:, 1]
auc = roc_auc_score(y_test, y_prob)

precision = precision_score(y_test, y_pred)

recall = recall_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred)

# Print the weights assigned to [LR_probabilities, KNN_probabilities]
print("Meta-estimator weights:", heart_net.final_estimator_.coef_)
print("\n===============================")
print(" Hybrid KNN + LR Results")
print("===============================\n")

print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1-score : {f1:.4f}")
print(f"ROC-AUC  : {auc:.4f}\n")
print(f"Mean CV Accuracy : {cv_result['test_accuracy'].mean()*100:.2f}%")
print(f"Mean CV AUC      : {cv_result['test_roc_auc'].mean():.4f}")
print(f"Mean CV Recall   : {cv_result['test_recall'].mean():.4f}")
print(f"Mean CV F1-Score : {cv_result['test_f1'].mean():.4f}\n")
print(
    f"Accuracy: {accuracy_score(y_test, y_pred)*100:.2f}%"
)
'''print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))'''

joblib.dump(heart_net, MODEL_PATH)
joblib.dump(scaler, SCALER_PATH)
joblib.dump(list(X.columns), COLUMNS_PATH)  # exact post-get_dummies column order
 
print(f"\nSaved model to     {MODEL_PATH.resolve()}")
print(f"Saved scaler to    {SCALER_PATH.resolve()}")
print(f"Saved columns to   {COLUMNS_PATH.resolve()}")
 
# Optionally also write metrics.json for the app's "Model Performance" expander:
import json
metrics_path = MODEL_DIR / "metrics.json"
existing = {}
if metrics_path.exists():
    with open(metrics_path) as f:
        existing = json.load(f)
 
existing["KNN + Logistic Regression (Stacked)"] = {
    "r2": None,  # not applicable for classification; app will just skip if missing
    "accuracy": float(accuracy_score(y_test, y_pred)),
    "precision": float(precision),
    "recall": float(recall),
    "f1": float(f1),
    "roc_auc": float(auc),
}
with open(metrics_path, "w") as f:
    json.dump(existing, f, indent=2)

'''MODEL_DIR = Path("robustness") / "Raw Dataset"
MODEL_DIR.mkdir(parents=True, exist_ok=True)'''
'''
train_sizes, train_scores, valid_scores = learning_curve(
    heart_net,
    X,
    y,
    cv=5,
    scoring="accuracy",
    train_sizes=np.linspace(0.1,1.0,10),
    random_state=42
)

train_mean = train_scores.mean(axis=1)
valid_mean = valid_scores.mean(axis=1)
print(train_mean)
print(valid_mean)

plt.figure(figsize=(8,6))

plt.plot(
    train_sizes,
    train_mean,
    marker="o",
    label="Training Accuracy"
)

plt.plot(
    train_sizes,
    valid_mean,
    marker="s",
    label="Validation Accuracy"
)

plt.title("Learning Curve")

plt.xlabel("Training Set Size")

plt.ylabel("Accuracy")

plt.legend()

plt.grid(True)

plt.savefig( MODEL_DIR / "OldDataset_learning_curve.png", dpi=300,)
'''


'''# Generate and plot the confusion matrix automatically
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Healthy", "Heart Disease"])
print("\nConfusion Matrix:\n", cm)

# Plot with a blue color map
disp.plot(cmap="Blues", values_format="d")

plt.title("Confusion Matrix", fontsize=14, fontweight='bold')

# Save the plot (Optional)
plt.savefig( MODEL_DIR / "OldDataset_confusion_matrix_sklearn.png", dpi=300, bbox_inches='tight')'''

'''# ROC Curve
fpr, tpr, thresholds = roc_curve(y_test, y_prob)


plt.figure(figsize=(6,6))
plt.plot(fpr, tpr, label=f"AUC = {auc:.4f}")
plt.plot([0,1], [0,1], linestyle='--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Receiver Operating Characteristic (ROC)")
plt.legend(loc="lower right")
plt.grid(True)
#plt.savefig( MODEL_DIR / "OldDataset_AUC-ROC.png", dpi=300)'''

'''
def hybrid_learning_curve(X, y, train_sizes=np.linspace(0.1, 1.0, 10), cv=5, random_state=42, n_repeats=5):
    """
    Manual learning curve for heart_net:
      StackingClassifier(
          estimators=[('lr', LogisticRegression), ('knn', KNeighborsClassifier)],
          final_estimator=LogisticRegression,
          stack_method='predict_proba'
      )
    At each (fraction, fold) we:
      1. Take a stratified subsample of the training split.
      2. Fit LR and KNN base models on the subsample.
      3. Stack their predict_proba outputs as meta-features.
      4. Fit the meta LogisticRegression on the stacked meta-features.
      5. Evaluate train & val accuracy using the meta model.
    """
    X = X.reset_index(drop=True)
    y = y.reset_index(drop=True)
    sizes_out, train_acc_out, val_acc_out = [], [], []
    for frac in train_sizes:
        n_sub = max(int(len(X_train) * frac), 20)


        rep_train_acc, rep_val_acc = [], []


        for rep in range(n_repeats):
            rng = np.random.RandomState(random_state + rep)
            sample_idx = rng.choice(X_train.index, size=n_sub, replace=False)


            X_sub, y_sub = X_train.loc[sample_idx], y_train.loc[sample_idx]


            if y_sub.nunique() < 2:
                continue

            # --- Base models (mirror heart_net's estimators) ---
            lr_base = LogisticRegression(random_state=random_state, C=0.01)
            k = min(29, len(X_sub) - 1)  # clamp so KNN never exceeds available samples
            knn_base = KNeighborsClassifier(n_neighbors=k, weights="uniform", metric="euclidean")
            lr_base.fit(X_sub, y_sub)
            knn_base.fit(X_sub, y_sub)

            # --- Stack predict_proba outputs as meta-features ---
            meta_sub = np.hstack((lr_base.predict_proba(X_sub), knn_base.predict_proba(X_sub)))
            meta_val = np.hstack((lr_base.predict_proba(X_test), knn_base.predict_proba(X_test)))

            # --- Meta estimator (mirror heart_net's final_estimator) ---
            lr_meta = LogisticRegression(C=1, random_state=random_state)
            lr_meta.fit(meta_sub, y_sub)
            rep_train_acc.append(accuracy_score(y_sub, lr_meta.predict(meta_sub)))
            rep_val_acc.append(accuracy_score(y_test, lr_meta.predict(meta_val)))


        sizes_out.append(n_sub)
        train_acc_out.append(np.mean(rep_train_acc))
        val_acc_out.append(np.mean(rep_val_acc))


    return np.array(sizes_out), np.array(train_acc_out), np.array(val_acc_out)

hybrid_sizes, hybrid_train_acc, hybrid_val_acc = hybrid_learning_curve(
    X_train,
    y_train,
    train_sizes=np.linspace(0.1, 1.0, 10),
    cv=5,
    random_state=42
)
plt.figure(figsize=(8, 6))
plt.plot(hybrid_sizes, hybrid_train_acc, marker="o", label="Training Accuracy (heart_net)")
plt.plot(hybrid_sizes, hybrid_val_acc, marker="s", label="Validation Accuracy (heart_net)")
plt.title("Hybrid Model Learning Curve (LR + KNN → LR Meta)")
plt.xlabel("Training Set Size")
plt.ylabel("Accuracy")
plt.legend()
plt.grid(True)
#plt.savefig(MODEL_DIR / "OldDataset_hybrid_learning_curve.png", dpi=300, bbox_inches="tight")
plt.show()
print("Saved plot: OldDataset_hybrid_learning_curve.png")
'''